fixes #527 path for entrypoint.sh
open-oni/open-oni pull request #528
Opened 2020-06-24 01:28 UTC by AndrewGearhart

- List changes with brief descriptions
  - Closes #527 

## Submitter Checklist

- [x] Verify all tests pass
  - Run tests with `docker-compose -f test-compose.yml -p onitest up test`
- [x] Update `README.md` and `docs/` as necessary
  - If a `manage.py` command is added, deleted, or modified its help text must
    be valid and it should be documented in detail in
    `docs/advanced/admin-commands.md`
- [x] Update `CHANGELOG.md`
  - Describe change(s) in appropriate section(s)
  - List self in Contributors section
  - If a release PR:
    - Replace `[Unreleased]` with version and update compare link
    - Update `core/version.py` with new version
- [x] Resolve merge conflicts
- [x] @mention individual(s) you would like to review the PR
  - Reviews for releases must come from a reviewer at another institution

## Reviewer Checklist

- [ ] Verify all tests pass
- [ ] Review changes for behavior, bugs, and compliance with [Development
  Standards](https://github.com/open-oni/open-oni/tree/dev/CONTRIBUTING.md#development-standards)
  - Request the submitter make any changes rather than pushing changes yourself.
    Otherwise ask another reviewer to look at any changes you have made.
- [ ] If a release, follow the [Release
  Checklist](https://github.com/open-oni/open-oni/tree/dev/CONTRIBUTING.md#release-checklist)

2020-06-25 00:13 UTC, AndrewGearhart reviewed
provides an intermediate fix for #520

2020-06-25 01:37 UTC, techgique submitted a review, later dismissed
Tests are now succeeding, and dev environment looks good too!

2020-06-25 02:23 UTC, techgique approved these changes
:+1:

2020-06-25 14:08 UTC, jechols requested changes
Overall a good move in the right direction, especially with how testing works, thanks!  I do have some questions and a strong reservation about the requirements.lock updates

2020-06-25 14:08 UTC, jechols commented on docker/.dockerignore
> +log/
Missing newline at end of file!

2020-06-25 14:08 UTC, jechols commented on docker/Dockerfile
> +RUN cp /opt/openoni/docker/entrypoint.sh /entrypoint.sh
Can you comment on this being copied via command rather than added as before?  I'm not sure why this was changed.

2020-06-25 14:08 UTC, jechols commented on requirements.lock
> -certifi==2019.11.28
Can you undo all these lockfile changes until we can sort out a better approach to this?  Major version updates should, at the least, include some slack discussion and their own PR

2022-03-08 20:04 UTC, techgique commented
Reminder to handle https://github.com/open-oni/open-oni/issues/526 after work on this and related PRs / issues

2026-05-20 21:29 UTC, techgique commented
This is really old and we're working on similar revision of containerization. I'm keeping the associated issues open as we might still want to adjust things for CI pipelines to start publishing images on Docker Hub. TBD

2026-05-20 21:29 UTC, closed without merging