Admin commands
open-oni/open-oni pull request #563
Opened 2020-10-02 19:56 UTC by jscancella

- List changes with brief descriptions
  - adding more documentation in the admin commands

2020-10-05 16:00 UTC, jechols approved these changes
I can't verify the windows stuff works, for though I run Windows, I don't have it set up in any way for doing development outside of WSL....  That said, this stuff all *looks* good to me.

2020-10-05 19:06 UTC, techgique requested changes
I think we'll want to drop or revert the first commit here that's being handled in #565. Otherwise, this looks great and ready to merge.

2020-10-05 19:13 UTC, jscancella commented
@techgique ugh, I did it again. I rebased to remove that commit, it should just be the admin commands now.

2020-10-30 21:06 UTC, techgique approved these changes

2020-10-30 21:06 UTC, merged