Correct Handling of Edition in lLinking of Issues
open-oni/open-oni pull request #571
Opened 2020-10-24 05:33 UTC by BusinessFawn

- List changes with brief descriptions
  - Closes #494 
Adds correct handling of edition in linking of issues in /core/templates/reports/batch.html and /core/templates/issues.html
Unremarkable changes so no update to  README/CHANGELOG

## Submitter Checklist

- [X] Verify all tests pass
  - Run tests with `docker-compose -f test-compose.yml -p onitest up test`
- [ ] Update `README.md` and `docs/` as necessary
  - [ ] If a `manage.py` command is added, deleted, or modified its help text must
    be valid and it should be documented in detail in
    `docs/advanced/admin-commands.md`
- Update `CHANGELOG.md`
  - [ ] Describe change(s) in appropriate section(s)
  - [ ] List self in Contributors section
- If a release PR:
  - [ ] In `CHANGELOG.md`, replace `[Unreleased]` with version and update compare link
  - [ ] Update `core/version.py` with new version
- [ ] Resolve merge conflicts
- [ ] @mention individual(s) you would like to review the PR
  - Reviews for releases must come from a reviewer at another institution

## Reviewer Checklist

- [ ] Verify all tests pass
- [ ] Review changes for behavior, bugs, and compliance with [Development
  Standards](https://github.com/open-oni/open-oni/tree/dev/CONTRIBUTING.md#development-standards)
  - Request the submitter make any changes rather than pushing changes yourself.
    Otherwise ask another reviewer to look at any changes you have made.
- [ ] If a release, follow the [Release
  Checklist](https://github.com/open-oni/open-oni/tree/dev/CONTRIBUTING.md#release-checklist)

2020-10-24 16:49 UTC, BusinessFawn commented
Seems like there is an problem rendering some data.. Pausing for the moment.

2020-10-24 23:07 UTC, BusinessFawn commented
Updated after some better testing. 

Showing my work:

Using [batch_mnhi_german_ver01](https://github.com/open-oni/sample-data/blob/master/batch_mnhi_german_ver01/data/sn83045350/00295876384/1878010301/1878010301_1.xml) updated to edition 101101.

```
<mods:detail type="edition">
  <mods:number>101101</mods:number>
</mods:detail>
```

Before: 

![Screen Shot 2020-10-24 at 7 01 59 PM](https://user-images.githubusercontent.com/15634295/97095289-807ccf00-162b-11eb-9456-241575743ded.png)
Which leads to (notice the link points to ed-1)
![Screen Shot 2020-10-24 at 7 02 15 PM](https://user-images.githubusercontent.com/15634295/97095291-87a3dd00-162b-11eb-92fb-54028d26219c.png)

After:

![Screen Shot 2020-10-24 at 7 05 30 PM](https://user-images.githubusercontent.com/15634295/97095322-fda84400-162b-11eb-84cf-d080625e6942.png)
![Screen Shot 2020-10-24 at 7 05 44 PM](https://user-images.githubusercontent.com/15634295/97095324-ff720780-162b-11eb-8486-e3b894c3d55b.png)

2020-10-29 23:41 UTC, techgique requested changes
Please make the suggested change to `core/templates/issue_pages.html`, unless I'm mistaken of course.

Also, a changelog entry for this would be preferred. Something like
```
### Fixed
- URLs/objects built with a static number `1` rather than edition number
```

And then add your name to the `Contributors` list :)

2020-10-29 23:41 UTC, techgique commented on core/templates/issue_pages.html
> +                        {% url 'openoni_issue_pages' title.lccn page_info.issue.date_issued 1 as url %}
I think you were on the right track here. From looking at the code for the URL a few lines above here, I think the appropriate fix is to replace `1` with `page_info.issue.edition`.

2020-10-30 20:36 UTC, techgique approved these changes

2020-10-30 20:37 UTC, merged