Update jQuery to 3.5.0
open-oni/open-oni pull request #578
Opened 2021-02-26 23:21 UTC by techgique

- Security vuln with HTML manipulation in the DOM appears not a risk due
  to not handling user input
  - https://jquery.com/upgrade-guide/3.5/
- `core/static/js/highlight.js` is handling hard-coded HTML, but appears
  unaffected in my review of the code and testing the functionality

## Submitter Checklist

- [x] Verify all tests pass
  - Run tests with `docker-compose -f test-compose.yml -p onitest up test`
- [x] Update `README.md` and `docs/` as necessary
  - [x] If a `manage.py` command is added, deleted, or modified its help text must
    be valid and it should be documented in detail in
    `docs/advanced/admin-commands.md`
- Copy the changelog entry file template in `changelogs/` to a new file in the
  same directory named following the `YYYY-MM-DD-branch_name.md` pattern with
  the day's date and your branch name
  - [x] Describe change(s) in appropriate section(s)
  - [x] List self in Contributors section
- If a release PR:
  - [x] Add individual changelog entry files from `changelogs/` to
    `CHANGELOG.md`, delete the `changelogs/` directory, replace `[Unreleased]`
    with version and update compare link
  - [x] Update `core/version.py` with new version
- [x] Resolve merge conflicts
- [x] @mention individual(s) you would like to review the PR
  - Reviews for releases must come from a reviewer at another institution

## Reviewer Checklist

- [ ] Verify all tests pass
- [ ] Review changes for behavior, bugs, and compliance with [Development
  Standards](https://github.com/open-oni/open-oni/tree/dev/CONTRIBUTING.md#development-standards)
  - Request the submitter make any changes rather than pushing changes yourself.
    Otherwise ask another reviewer to look at any changes you have made.
- [ ] If a release, follow the [Release
  Checklist](https://github.com/open-oni/open-oni/tree/dev/CONTRIBUTING.md#release-checklist)

2021-02-26 23:22 UTC, techgique commented
For your convenience:
https://github.com/open-oni/open-oni/blob/dev/core/static/js/highlight.js

The map plugin also does some hard-coded HTML manipulation and appears unaffected as well in my code review and testing:
https://github.com/open-oni/plugin_map/blob/feature/update-leaflet/static/js/map.js

2021-03-02 16:50 UTC, jechols commented
Let's go with jquery 3.5.1: https://blog.jquery.com/2020/05/04/jquery-3-5-1-released-fixing-a-regression/

It doesn't seem to have any incompatible changes vs. 3.5.0, and potentially prevents other incompatibilities.

2021-03-02 16:51 UTC, jechols requested changes
Switch to 3.5.1

2021-03-11 15:19 UTC, jechols approved these changes

2021-03-11 15:19 UTC, merged